name: Release

on:
  push:
    tags: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name_suffix: linux
            path_suffix: ""
          - os: macos-latest
            name_suffix: macos
            path_suffix: ""
          - os: windows-latest
            name_suffix: windows
            path_suffix: .exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: sort_vis_${{ matrix.name_suffix }}
          path: target/release/sort_vis${{ matrix.path_suffix }}
