name: Release

on:
  push:
    tags: [ "v*.*.*" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name_suffix: linux
            path_suffix: ""
          - os: macos-latest
            name_suffix: macos
            path_suffix: ""
          - os: windows-latest
            name_suffix: windows
            path_suffix: .exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Build executable
        run: cargo build --profile dist

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: sort_vis_${{ matrix.name_suffix }}
          path: target/dist/sort_vis${{ matrix.path_suffix }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
      - name: Create archive for all executables
        run: |
          zstdmt -10 sort_vis_linux/sort_vis -o sort_vis_linux.zst
          zstdmt -10 sort_vis_macos/sort_vis -o sort_vis_macos.zst
          zip sort_vis_windows.zip sort_vis_windows/sort_vis.exe

      - name: Create a release with all executables
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sort_vis_linux.zst
            sort_vis_macos.zst
            sort_vis_windows.zip
